[package]
name = "fluent_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
html5ever = "0.26.0"
kuchikiki = "0.8.2"
lightningcss = { version = "1.0.0-alpha.45", default-features = false, features = [
    "visitor",
    "rayon",
    "grid",
] }
markup5ever = "0.11.0"
prettyplease = "0.2.12"
proc-macro2 = "1.0.66"
quote = "1.0.33"
syn = { version = "2.0.29", features = ["parsing", "printing", "proc-macro"] }
uuid = { version = "1.4.1", features = ["v4"] }
